sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test:ci

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage